---
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
APPLY_FIXES: all
DISABLE_LINTERS:
  - CSHARP_DOTNET_FORMAT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
  - SPELL_LYCHEE
